import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import AuthContextProvider from "@/context/AuthContext";
import WebSocketProvider from "@/context/WebSocketContext";

import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AuthContextProvider>
            <WebSocketProvider>
                <html lang="en">
                    <body className={inter.className}>
                        <Header />
                        {children}
                        <Toaster
                            position="top-center"
                            reverseOrder={false}
                            gutter={8}
                        />
                    </body>
                </html>
            </WebSocketProvider>
        </AuthContextProvider>
    );
}
